// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: sms.proto

package sms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//In practice, TemplateId and SignId in pushing service are always virtual
//to tolerant backend service changing.
type PushSMSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber      []string `protobuf:"bytes,1,rep,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	TemplateParamSet []string `protobuf:"bytes,2,rep,name=TemplateParamSet,proto3" json:"TemplateParamSet,omitempty"`
	TemplateId       string   `protobuf:"bytes,3,opt,name=TemplateId,proto3" json:"TemplateId,omitempty"`
	SignId           string   `protobuf:"bytes,4,opt,name=SignId,proto3" json:"SignId,omitempty"`
}

func (x *PushSMSRequest) Reset() {
	*x = PushSMSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSMSRequest) ProtoMessage() {}

func (x *PushSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSMSRequest.ProtoReflect.Descriptor instead.
func (*PushSMSRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{0}
}

func (x *PushSMSRequest) GetPhoneNumber() []string {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *PushSMSRequest) GetTemplateParamSet() []string {
	if x != nil {
		return x.TemplateParamSet
	}
	return nil
}

func (x *PushSMSRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *PushSMSRequest) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

type PushSMSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SMSStatus []*SMSStatus `protobuf:"bytes,1,rep,name=SMSStatus,proto3" json:"SMSStatus,omitempty"`
}

func (x *PushSMSResponse) Reset() {
	*x = PushSMSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushSMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSMSResponse) ProtoMessage() {}

func (x *PushSMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSMSResponse.ProtoReflect.Descriptor instead.
func (*PushSMSResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{1}
}

func (x *PushSMSResponse) GetSMSStatus() []*SMSStatus {
	if x != nil {
		return x.SMSStatus
	}
	return nil
}

type SMSStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SerialNo    string `protobuf:"bytes,1,opt,name=SerialNo,proto3" json:"SerialNo,omitempty"`
	PhoneNumber string `protobuf:"bytes,2,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Fee         uint64 `protobuf:"varint,3,opt,name=Fee,proto3" json:"Fee,omitempty"`
	ErrCode     string `protobuf:"bytes,4,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	Message     string `protobuf:"bytes,5,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *SMSStatus) Reset() {
	*x = SMSStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSStatus) ProtoMessage() {}

func (x *SMSStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSStatus.ProtoReflect.Descriptor instead.
func (*SMSStatus) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{2}
}

func (x *SMSStatus) GetSerialNo() string {
	if x != nil {
		return x.SerialNo
	}
	return ""
}

func (x *SMSStatus) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SMSStatus) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *SMSStatus) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

func (x *SMSStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddSMSSignatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signatures []*SMSSignature `protobuf:"bytes,1,rep,name=Signatures,proto3" json:"Signatures,omitempty"`
}

func (x *AddSMSSignatureRequest) Reset() {
	*x = AddSMSSignatureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSMSSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSMSSignatureRequest) ProtoMessage() {}

func (x *AddSMSSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSMSSignatureRequest.ProtoReflect.Descriptor instead.
func (*AddSMSSignatureRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{3}
}

func (x *AddSMSSignatureRequest) GetSignatures() []*SMSSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type SMSSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignId      string `protobuf:"bytes,1,opt,name=SignId,proto3" json:"SignId,omitempty"`
	SignContent string `protobuf:"bytes,2,opt,name=SignContent,proto3" json:"SignContent,omitempty"`
}

func (x *SMSSignature) Reset() {
	*x = SMSSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSSignature) ProtoMessage() {}

func (x *SMSSignature) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSSignature.ProtoReflect.Descriptor instead.
func (*SMSSignature) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{4}
}

func (x *SMSSignature) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *SMSSignature) GetSignContent() string {
	if x != nil {
		return x.SignContent
	}
	return ""
}

type AddSMSTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Templates []*SMSTemplate `protobuf:"bytes,1,rep,name=Templates,proto3" json:"Templates,omitempty"`
}

func (x *AddSMSTemplateRequest) Reset() {
	*x = AddSMSTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSMSTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSMSTemplateRequest) ProtoMessage() {}

func (x *AddSMSTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSMSTemplateRequest.ProtoReflect.Descriptor instead.
func (*AddSMSTemplateRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{5}
}

func (x *AddSMSTemplateRequest) GetTemplates() []*SMSTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type SMSTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId  string `protobuf:"bytes,1,opt,name=TemplateId,proto3" json:"TemplateId,omitempty"`
	SignContent string `protobuf:"bytes,2,opt,name=SignContent,proto3" json:"SignContent,omitempty"`
	ParamNumber int32  `protobuf:"varint,3,opt,name=ParamNumber,proto3" json:"ParamNumber,omitempty"`
}

func (x *SMSTemplate) Reset() {
	*x = SMSTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSTemplate) ProtoMessage() {}

func (x *SMSTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSTemplate.ProtoReflect.Descriptor instead.
func (*SMSTemplate) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{6}
}

func (x *SMSTemplate) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SMSTemplate) GetSignContent() string {
	if x != nil {
		return x.SignContent
	}
	return ""
}

func (x *SMSTemplate) GetParamNumber() int32 {
	if x != nil {
		return x.ParamNumber
	}
	return 0
}

type GetAllTemplatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllTemplatesRequest) Reset() {
	*x = GetAllTemplatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTemplatesRequest) ProtoMessage() {}

func (x *GetAllTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTemplatesRequest.ProtoReflect.Descriptor instead.
func (*GetAllTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{7}
}

type GetAllTemplatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllTemplatesResponse) Reset() {
	*x = GetAllTemplatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTemplatesResponse) ProtoMessage() {}

func (x *GetAllTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTemplatesResponse.ProtoReflect.Descriptor instead.
func (*GetAllTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{8}
}

//
//Id is the virtual id mapping to the real signId / templateId
type UniformResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status []*AddStatus `protobuf:"bytes,1,rep,name=Status,proto3" json:"Status,omitempty"`
}

func (x *UniformResponse) Reset() {
	*x = UniformResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniformResponse) ProtoMessage() {}

func (x *UniformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniformResponse.ProtoReflect.Descriptor instead.
func (*UniformResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{9}
}

func (x *UniformResponse) GetStatus() []*AddStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AddStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *AddStatus) Reset() {
	*x = AddStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStatus) ProtoMessage() {}

func (x *AddStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStatus.ProtoReflect.Descriptor instead.
func (*AddStatus) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{10}
}

func (x *AddStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_sms_proto protoreflect.FileDescriptor

var file_sms_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x6d, 0x73,
	0x22, 0x96, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x10, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x53, 0x65,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x0f, 0x50, 0x75, 0x73,
	0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x09,
	0x53, 0x4d, 0x53, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x4d, 0x53, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x09, 0x53, 0x4d, 0x53, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x09, 0x53,
	0x4d, 0x53, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x4e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x46, 0x65, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x46, 0x65, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4b, 0x0a, 0x16,
	0x41, 0x64, 0x64, 0x53, 0x4d, 0x53, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6d, 0x73,
	0x2e, 0x53, 0x4d, 0x53, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0a, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x48, 0x0a, 0x0c, 0x53, 0x4d, 0x53,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x69, 0x67,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x47, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x09, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x22, 0x71, 0x0a, 0x0b,
	0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53,
	0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x0f, 0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x4f, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x32, 0x9a, 0x02, 0x0a, 0x0a, 0x53, 0x4d, 0x53, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x34, 0x0a, 0x07, 0x50, 0x75, 0x73, 0x68, 0x53, 0x4d, 0x53, 0x12, 0x13, 0x2e, 0x73, 0x6d, 0x73,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x4d, 0x53, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1b, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x41,
	0x64, 0x64, 0x53, 0x4d, 0x53, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x55, 0x6e, 0x69, 0x66,
	0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x41,
	0x64, 0x64, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e,
	0x73, 0x6d, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x4d, 0x53, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x6d, 0x73, 0x2e,
	0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x12, 0x1b, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x55, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x73, 0x6d, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sms_proto_rawDescOnce sync.Once
	file_sms_proto_rawDescData = file_sms_proto_rawDesc
)

func file_sms_proto_rawDescGZIP() []byte {
	file_sms_proto_rawDescOnce.Do(func() {
		file_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_sms_proto_rawDescData)
	})
	return file_sms_proto_rawDescData
}

var file_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sms_proto_goTypes = []interface{}{
	(*PushSMSRequest)(nil),          // 0: sms.PushSMSRequest
	(*PushSMSResponse)(nil),         // 1: sms.PushSMSResponse
	(*SMSStatus)(nil),               // 2: sms.SMSStatus
	(*AddSMSSignatureRequest)(nil),  // 3: sms.AddSMSSignatureRequest
	(*SMSSignature)(nil),            // 4: sms.SMSSignature
	(*AddSMSTemplateRequest)(nil),   // 5: sms.AddSMSTemplateRequest
	(*SMSTemplate)(nil),             // 6: sms.SMSTemplate
	(*GetAllTemplatesRequest)(nil),  // 7: sms.GetAllTemplatesRequest
	(*GetAllTemplatesResponse)(nil), // 8: sms.GetAllTemplatesResponse
	(*UniformResponse)(nil),         // 9: sms.UniformResponse
	(*AddStatus)(nil),               // 10: sms.AddStatus
}
var file_sms_proto_depIdxs = []int32{
	2,  // 0: sms.PushSMSResponse.SMSStatus:type_name -> sms.SMSStatus
	4,  // 1: sms.AddSMSSignatureRequest.Signatures:type_name -> sms.SMSSignature
	6,  // 2: sms.AddSMSTemplateRequest.Templates:type_name -> sms.SMSTemplate
	10, // 3: sms.UniformResponse.Status:type_name -> sms.AddStatus
	0,  // 4: sms.SMSService.PushSMS:input_type -> sms.PushSMSRequest
	3,  // 5: sms.SMSService.AddSMSSignature:input_type -> sms.AddSMSSignatureRequest
	5,  // 6: sms.SMSService.AddSMSTemplate:input_type -> sms.AddSMSTemplateRequest
	7,  // 7: sms.SMSService.GetAllTemplates:input_type -> sms.GetAllTemplatesRequest
	1,  // 8: sms.SMSService.PushSMS:output_type -> sms.PushSMSResponse
	9,  // 9: sms.SMSService.AddSMSSignature:output_type -> sms.UniformResponse
	9,  // 10: sms.SMSService.AddSMSTemplate:output_type -> sms.UniformResponse
	8,  // 11: sms.SMSService.GetAllTemplates:output_type -> sms.GetAllTemplatesResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_sms_proto_init() }
func file_sms_proto_init() {
	if File_sms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushSMSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushSMSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSMSSignatureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSMSTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllTemplatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllTemplatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniformResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sms_proto_goTypes,
		DependencyIndexes: file_sms_proto_depIdxs,
		MessageInfos:      file_sms_proto_msgTypes,
	}.Build()
	File_sms_proto = out.File
	file_sms_proto_rawDesc = nil
	file_sms_proto_goTypes = nil
	file_sms_proto_depIdxs = nil
}
